import img1 from "../Assets/Png/15.jpg";
import img2 from "../Assets/Png/16.jpg";
import img3 from "../Assets/Png/17.jpg";
import img4 from "../Assets/Png/18.jpg";
import img5 from "../Assets/Png/19.jpg";
import img6 from "../Assets/Png/20.jpg";
import img7 from "../Assets/Png/21.jpg";
import img8 from "../Assets/Png/22.jpg";
import img9 from "../Assets/Png/23.jpg";
import img10 from "../Assets/Png/24.jpg";
import img11 from "../Assets/Png/25.jpg";
import img12 from "../Assets/Png/26.jpg";
import img13 from "../Assets/Png/27.jpg";
import img14 from "../Assets/Png/28.jpg";
import img15 from "../Assets/Png/29.jpg";
import img16 from "../Assets/Png/30.jpg";
import img17 from "../Assets/Png/31.jpg";
import img18 from "../Assets/Png/32.jpg";
import img19 from "../Assets/Png/33.jpg";
import img20 from "../Assets/Png/34.jpg";
import img21 from "../Assets/Png/35.jpg";
import img22 from "../Assets/Png/36.jpg";
import img23 from "../Assets/Png/37.jpg";
import img24 from "../Assets/Png/38.jpg";
import img25 from "../Assets/Png/39.jpg";
import img26 from "../Assets/Png/40.jpg";
import img27 from "../Assets/Png/41.jpg";
import img28 from "../Assets/Png/42.jpg";
import img29 from "../Assets/Png/43.jpg";
import img30 from "../Assets/Png/44.jpg";
import img31 from "../Assets/Png/45.jpg";

export const db1 = [
  {
    id: 1,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",
    picture: img1,
    header: "یخچال سامسونگ",
    paragraph: "یخچال فریزر 4 در فلکس هوشمند سامسونگ با ظرفیت فوق العاده بالا",
    code: "1",
    price: 6000000,
    currentPrice: 6500000,
    discount: "0.07",
    details: "",
  },
  {
    id: 2,
    product: "cellphone",
    category: "electronic",
    brand: "iphone",
    picture: img2,
    header: "آیفون 13 پرومکس",
    paragraph:
      "این محصول در صورت لزوم بازرسی، تست و بازسازی می شود",
    code: "2",
    price: 3500000,
    currentPrice: 4000000,
    discount: "0.12",
    details: "",
  },
  {
    id: 3,
    product: "shoes",
    category: "cloth",
    brand: "adidas",
    picture: img3,
    header: "کفش زنانه آدیداس",
    paragraph:
      "این کفش بسیار نرم و راحت و مناسب با سلیقه خانم ها می باشد ",
    code: "3",
    price: 2500000,
    currentPrice: 3000000,
    discount: "0.16",
    details: "",
  },
  {
    id: 4,
    product: "pencils",
    category: "stationary",
    brand: "faber-castell",
    picture: img4,
    header: "مداد رنگی فابرکاستل",
    paragraph:
      "رنگ های روشن و درخشان. از جمله رنگ های متالیک، نئون و پاستلی",
    code: "4",
    price: 1000000,
    currentPrice: 1500000,
    discount: "0.33",
    details: "",
  },
  {
    id: 5,
    product: "laptop",
    category: "electronic",
    brand: "apple",
    picture: img5,
    header: "مک بوک اپل",
    paragraph: "مک بوک اپل با صفحه لمسی یکی از جدید ترین و راحت ترین لپتاپها",
    code: "5",
    price: 23000000,
    currentPrice: 24000000,
    discount: 0.04,
    details: "",
  },
  {
    id: 6,
    product: "paper",
    category: "stationary",
    brand: "copymax",
    picture: img6,
    header: "برگه آ چهار",
    paragraph: "بسته 500 تایی برگه آچهار کپی مکس با بهترین قیمت",
    code: "6",
    price: 350000,
    currentPrice: 400000,
    discount: "0.12",
    details: "",
  },
  {
    id: 7,
    product: "shoes",
    category: "cloth",
    brand: "adidas",
    picture: img7,
    header: "کفش آدیداس مردانه",
    paragraph: "کفش های تنیس مردانه که برای تمرین و اجرا ساخته شده اند",
    code: "7",
    price: 2500000,
    currentPrice: 3000000,
    discount: "0.16",
    details: "",
  },
  {
    id: 8,
    product: "coffee",
    category: "kitchen",
    brand: "nova",
    picture: img8,
    header: "قهوه ساز نووا",
    paragraph: "طراحی شده برای دم کردن قهوه با گرم کردن و فیلتر کردن آب",
    code: "8",
    price: 1300000,
    currentPrice: 2000000,
    discount: "0.35",
    details: "",
  },
  {
    id: 9,
    product: "coffee",
    category: "kitchen",
    brand: "nova",
    picture: img9,
    header: "قهوه ساز نووا",
    paragraph: "طراحی شده برای دم کردن قهوه با گرم کردن و فیلتر کردن آب",
    code: "9",
    price: 1700000,
    currentPrice: 2000000,
    discount: "0.15",
    details: "",
  },
  {
    id: 10,
    product: "pot",
    category: "kitchen",
    brand: "vogati",
    picture: img10,
    header: "قابلمه ووگاتی",
    paragraph: "فولاد ضد زنگ، چدن یا نچسب و اشکال مختلف با طرحی بسیار زیبا",
    code: "10",
    price: 3200000,
    currentPrice: 3800000,
    discount: "0.15",
    details: "",
  },
  {
    id: 11,
    product: "pot",
    category: "kitchen",
    brand: "vogati",
    picture: img11,
    header: "قابلمه ووگاتی",
    paragraph: "فولاد ضد زنگ، چدن یا نچسب و اشکال مختلف با طرحی بسیار زیبا",
    code: "11",
    price: 2700000,
    currentPrice: 3200000,
    discount: "0.15",
    details: "",
  },
  {
    id: 12,
    product: "iron",
    category: "kitchen",
    brand: "delmonti",
    picture: img12,
    header: "اتو دلمونتی",
    paragraph: "این آهن به دلیل استحکام، دوام و توانایی خود شناخته شده است",
    code: "12",
    price: 1800000,
    currentPrice: 2300000,
    discount: "0.21",
    details: "",
  },
  {
    id: 13,
    product: "iron",
    category: "kitchen",
    brand: "delmonti",
    picture: img13,
    header: "اتو دلمونتی",
    paragraph: "این آهن به دلیل استحکام، دوام و توانایی خود شناخته شده است",
    code: "13",
    price: 1800000,
    currentPrice: 2300000,
    discount: "0.21",
    details: "",
  },
  {
    id: 14,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",
    picture: img14,
    header: "یخچال سامسونگ",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "14",
    price: 22000000,
    currentPrice: 24000000,
    discount: "0.04",
    details: "",
  },
  {
    id: 15,
    product: "refrigerator",
    category: "kitchen",
    brand: "samsung",
    picture: img15,
    header: "یخچال سامسونگ",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "15",
    price: 22000000,
    currentPrice: 24000000,
    discount: "0.04",
    details: "",
  },
  {
    id: 16,
    product: "refrigerator",
    category: "kitchen",
    brand: "lg",
    picture: img16,
    header: "یخچال ال جی",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "16",
    price: 18000000,
    currentPrice: 20000000,
    discount: "0.1",
    details: "",
  },
  {
    id: 17,
    product: "refrigerator",
    category: "kitchen",
    brand: "lg",
    picture: img17,
    header: "یخچال ال جی",
    paragraph: "انتخاب محبوب در بین مصرف کنندگان به دلیل بهره وری انرژی آن است",
    code: "17",
    price: 18000000,
    currentPrice: 20000000,
    discount: "0.1",
    details: "",
  },
  {
    id: 18,
    product: "cellphone",
    category: "electronic",
    brand: "samsung",
    picture: img18,
    header: "موبایل سامسونگ",
    paragraph: "طیف گسترده ای از تلفن های همراه که نیازهای مختلف رافراهم میکند",
    code: "18",
    price: 14000000,
    currentPrice: 16000000,
    discount: "0.12",
    details: "",
  },
  {
    id: 19,
    product: "cellphone",
    category: "electronic",
    brand: "xiaomi",
    picture: img19,
    header: "موبایل شیاومی",
    paragraph: "طیف گسترده ای از تلفن های همراه که نیازهای مختلف رافراهم میکند",
    code: "19",
    price: 17000000,
    currentPrice: 18000000,
    discount: "0.05",
    details: "",
  },
  {
    id: 20,
    product: "mobile-accessory",
    category: "electronic",
    brand: "iphone",
    picture: img20,
    header: "ایرپاد اپل",
    paragraph: "هدفون های بی سیم طراحی شده برای ادغام با دستگاه های اپل",
    code: "20",
    price: 4500000,
    currentPrice: 5000000,
    discount: "0.1",
    details: "",
  },
  {
    id: 21,
    product: "mobile-accessory",
    category: "electronic",
    brand: "samsung",
    picture: img21,
    header: "محافظ صفحه سامسونگ",
    paragraph:
      " لوازم جانبی محافظ که برای گوشی های هوشمند سامسونگ طراحی شده است",
    code: "21",
    price: 300000,
    currentPrice: 450000,
    discount: "0.11",
    details: "",
  },
  {
    id: 22,
    product: "mobile-accessory",
    category: "electronic",
    brand: "xiaomi",
    picture: img22,
    header: "محافظ صفحه شیاومی",
    paragraph:
      "یک لوازم جانبی محافظ که برای گوشی های هوشمند سامسونگ طراحی شده است",
    code: "22",
    price: 300000,
    currentPrice: 450000,
    discount: "0.11",
    details: "",
  },
  {
    id: 23,
    product: "laptop",
    category: "electronic",
    brand: "hp",
    picture: img23,
    header: "لپتاپ اچ پی",
    paragraph: "طیف گسترده ای از لپ تاپ که نیازهای کاربران را برآورده می کنند",
    code: "23",
    price: 38000000,
    currentPrice: 40000000,
    discount: "0.05",
    details: "",
  },
  {
    id: 24,
    product: "laptop",
    category: "electronic",
    brand: "lenovo",
    picture: img24,
    header: "لپتاپ لنووو",
    paragraph: "طیف گسترده ای از لپ تاپ که نیازهای کاربران را برآورده می کنند",
    code: "24",
    price: 38000000,
    currentPrice: 40000000,
    discount: "0.05",
    details: "",
  },
  {
    id: 25,
    product: "laptop-accessory",
    category: "electronic",
    brand: "apple",
    picture: img25,
    header: "مووس اپل",
    paragraph: "اولین بار در سال 1998 معرفی شد و به دلیل طراحی خود شناخته شده است",
    code: "25",
    price: 4200000,
    currentPrice: 5000000,
    discount: "0.16",
    details: "",
  },
  {
    id: 26,
    product: "laptop-accessory",
    category: "electronic",
    brand: "sony",
    picture: img26,
    header: "هدفون سونی",
    paragraph: "انتخاب های محبوب به دلیل فناوری صدای با کیفیت بالا",
    code: "26",
    price: 3000000,
    currentPrice: 3700000,
    discount: "0.18",
    details: "",
  },
  {
    id: 27,
    product: "laptop-accessory",
    category: "electronic",
    brand: "apple",
    picture: img27,
    header: "کیبورد اپل",
    paragraph: "اولین بار در سال 1998 معرفی شد و به دلیل طراحی خود شناخته شده است",
    code: "27",
    price: 6200000,
    currentPrice: 7500000,
    discount: "0.17",
    details: "",
  },
  {
    id: 28,
    product: "pc-accessory",
    category: "electronic",
    brand: "intel",
    picture: img28,
    header: "مادربورد اینتل",
    paragraph:
      " برد اصلی در یک سیستم که اجزای سخت افزاری را به هم متصل می کند",
    code: "28",
    price: 36000000,
    currentPrice: 38000000,
    discount: "0.05",
    details: "",
  },
  {
    id: 29,
    product: "pc-accessory",
    category: "electronic",
    brand: "nvidia",
    picture: img29,
    header: "هارد انویدیا",
    paragraph:
      "به دلیل های سخت افزار خود در واحد پردازش گرافیکی شناخته شده است",
    code: "29",
    price: 24000000,
    currentPrice: 26000000,
    discount: "0.07",
    details: "",
  },
  {
    id: 30,
    product: "t-shirt",
    category: "cloth",
    brand: "nike",
    picture: img30,
    header: "تیشرت نایک",
    paragraph:
      "این محصول در سبک ها، رنگ ها و طرح های مختلف مختلف عرضه می شود",
    code: "30",
    price: 1400000,
    currentPrice: 1900000,
    discount: "0.26",
    details: "",
  },
  {
    id: 31,
    product: "t-shirt",
    category: "cloth",
    brand: "puma",
    picture: img31,
    header: "تیشرت پوما",
    paragraph:
      "این محصول در سبک ها، رنگ ها و طرح های مختلف  مختلف عرضه می شود",
    code: "31",
    price: 1400000,
    currentPrice: 1900000,
    discount: "",
    details: "",
  },
];
