export const UserProfileData1 = {
    text1 : "سفارشات",
    text2 : "دیدگاه ها",
    text3 : "آدرس ها",
    text4 : "پشتیبانی",
    text5 : "حساب کاربری",
    text6 : "خوش آمدید",
    text7 : "فیلتر",
    text8 : "نام کالا",
    text9 : "نوع سفارش",
    text10 : "کد سفارش",
    text11 : "تاریخ سفارش",
    text12 : "ساعت سفارش",
    text13 : "مبلغ",
    text14 : "",
}