import tasviehIcon from "../Assets/Svg/TasvieIcon.svg";
import bankIcon from "../Assets/Svg/BankAccountIcon.svg";
import tarakoneshIcon from "../Assets/Svg/TarakoneshIcon.svg";
import sayerIcon from "../Assets/Svg/SayerIcon.svg";
import pishkhanIcon from "../Assets/Svg/PishkhanIcon.svg";
import mahsulatIcon from "../Assets/Svg/MahsulatIcon.svg";
import dargahIcon from "../Assets/Svg/DargahIcon.svg";

export const UserProfileData1 = {
  text1: "سفارشات",
  text2: "دیدگاه ها",
  text3: "آدرس ها",
  text4: "پشتیبانی",
  text5: "حساب کاربری",
  text6: "خوش آمدید",
  text7: "فیلتر",
  text8: "نام کالا",
  text9: "نوع سفارش",
  text10: "کد سفارش",
  text11: "تاریخ سفارش",
  text12: "ساعت سفارش",
  text13: "مبلغ",
  text14: "حذف همه دیدگاه ها",
  text15: "دسته بندی",
  text16: "نام کالا",
  text17: "کدسفارش",
  text18: "متن دیدگاه",
  text19: "عکس کالا",
  text20: "آدرس های ثبت شده",
  text21: "ویرایش اطلاعات",
  text22: "آدرس",
  text23: "استان",
  text24: "کد پستی",
  text25: "شماره تماس",
  text26: "نام و نام خانوادگی",
  text27: "گیرنده",
  text28: "واحد امور مشتریان آرین شاپ",
  text29: "",
  text30: "",
  text31: "",
  text32: "",
  text33: "",
  text34: "",
  text35: "",
  text36: "",
  text37: "",
  text38: "",
};

export const UserProfileData2 = [
  {
    id: 1,
    myUsCardAlt: "تسویه حساب",
    myUsCardSrc: tasviehIcon,
    myUsCardWidth: "55px",
    myUsCardHeight: "51px",
    myUsCardText: "تسویه حساب",
  },
  {
    id: 2,
    myUsCardAlt: "حساب بانکی",
    myUsCardSrc: bankIcon,
    myUsCardWidth: "49px",
    myUsCardHeight: "51px",
    myUsCardText: "حساب بانکی",
  },
  {
    id: 3,
    myUsCardAlt: "تراکنش",
    myUsCardSrc: tarakoneshIcon,
    myUsCardWidth: "47px",
    myUsCardHeight: "47px",
    myUsCardText: "تراکنش",
  },
  {
    id: 4,
    myUsCardAlt: "اینماد",
    myUsCardSrc: tasviehIcon,
    myUsCardWidth: "55px",
    myUsCardHeight: "51px",
    myUsCardText: "اینماد",
  },
  {
    id: 5,
    myUsCardAlt: "سایر موارد",
    myUsCardSrc: sayerIcon,
    myUsCardWidth: "56px",
    myUsCardHeight: "42px",
    myUsCardText: "سایر موارد",
  },
  {
    id: 6,
    myUsCardAlt: "پیشخوان",
    myUsCardSrc: pishkhanIcon,
    myUsCardWidth: "40px",
    myUsCardHeight: "48px",
    myUsCardText: "پیشخوان",
  },
  {
    id: 7,
    myUsCardAlt: "محصولات",
    myUsCardSrc: mahsulatIcon,
    myUsCardWidth: "44px",
    myUsCardHeight: "47px",
    myUsCardText: "محصولات",
  },
  {
    id: 8,
    myUsCardAlt: "درگاه پرداخت",
    myUsCardSrc: dargahIcon,
    myUsCardWidth: "46px",
    myUsCardHeight: "41px",
    myUsCardText: "درگاه پرداخت",
  },
];
